name       : syndication
version    : 5.80.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/syndication-5.80.0.tar.xz : 10f2273b87e89f2ea73baee66a8b1cc993acea96d74be29f99ac631145f742c8
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - kcodecs-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
