name       : syndication
version    : 5.69.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/syndication-5.69.0.tar.xz : eb38fbc7749efff7a06ee1454c0aaf4e0751bda2eaaf2587560e7d810f02972e
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
