name       : syndication
version    : 5.83.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/syndication-5.83.0.tar.xz : 5fdfa819dd43c4b7c31a3014b080c2e5c09e312a19e6858907da79fd0d42e25f
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
optimize   : lto
builddeps  :
    - kcodecs-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
