name       : syndication
version    : 5.68.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/syndication-5.68.0.tar.xz : 0715fc1b7312b5081521b781d0878d88cc70dcb77272ee173cecca03cc221fd3
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
