name       : syndication
version    : 17.12.2
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/syndication-17.12.2.tar.xz : 8011fe1c0c8afd5e6f148b0bfc8fcb3e2c1f8165a44ae76576f7e67615988dc1
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
