name       : syndication
version    : 5.107.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.107/syndication-5.107.0.tar.xz : 254d38c51f77e3e98b78761490258d394151f07b5e5ad19113061ff5c9b0f84a
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
optimize   : lto
builddeps  :
    - kcodecs-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
