name       : syndication
version    : 5.53.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/syndication-5.53.0.tar.xz : cbe4bfbbfdd90401574a6c60463ffa08083ad14efac0d0ed888c04d85e46d27e
license    : LGPL-2.1-or-later
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
