name       : syndication
version    : 5.64.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/syndication-5.64.0.tar.xz : bffcd673a70646c8cb683ed7b26f6ef251a2ffe439fc78123ccee4332b567b57
license    : LGPL-2.1-or-later
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
