name       : syndication
version    : 18.04.1
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/syndication-18.04.1.tar.xz : a562e48be03cd20165996f973615590d1ac4e1b1de98164ec926ff8715d08abd
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming.library
optimize   : lto
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
