name       : syndication
version    : 17.12.1
release    : 3
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/syndication-17.12.1.tar.xz : 01a4c1fa843de8e8b5c4b747edf6ddcf898e538adb499801f42c19d656d616f9
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
