name       : syndication
version    : 5.51.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/syndication-5.51.0.tar.xz : cea7c8f735f7c20b1c35124d4b8d2ab44494d24ca20ba0c408492156f97cfe59
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
