name       : syndication
version    : 5.109.0
release    : 62
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/syndication-5.109.0.tar.xz : 2561a206b8e1e51bee3a5888429335ce4dbf4c9fd1f8c112f6089a2dd3d815ca
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
optimize   : lto
builddeps  :
    - kcodecs-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
