name       : syndication
version    : 5.90.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.90/syndication-5.90.0.tar.xz : bdfe30c05bbdd8e10903fe69a37cf859f25984edae16283fdd5c0ac207213229
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
optimize   : lto
builddeps  :
    - kcodecs-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
