name       : syndication
version    : 18.08.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/syndication-18.08.0.tar.xz : e1b411f59a90e7f0d66480f2ccb31b5c97a8dcfa0bd5bc693877e4ba8e9e439e
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
