name       : syndication
version    : '5.50'
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/syndication-5.50.0.tar.xz : 6355e2b14966e455dd0d6fd9cdb6691e905ab62be1981b9efbfb3727305de3c4
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
