name       : syndication
version    : 5.63.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/syndication-5.63.0.tar.xz : e609c7f36559d6081d4ffe5c3cf995d96c620f18550f14f274d4c717423713b4
license    : LGPL-2.1-or-later
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
