name       : syndication
version    : 5.87.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.87/syndication-5.87.0.tar.xz : 7a21f7c335425421695fcb290a3f5037d8b4c9b946377b7200f3e357f5407af5
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
optimize   : lto
builddeps  :
    - kcodecs-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
