name       : syndication
version    : 5.76.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/syndication-5.76.0.tar.xz : 239ec30ff8f7ad2911ecc6b9b9c32f2b44c6cad634900105936ae56bf96d6292
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
