name       : syndication
version    : 17.08.3
release    : 2
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/syndication-17.08.3.tar.xz : 1091937d0afd04be12678209163f979d857f416af49d17da4d2ddf2312fe5379
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
