name       : syndication
version    : 5.65.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/syndication-5.65.0.tar.xz : 1be1bd32b4c75c6bb1b35d67cc7643089e0c525cb30e392220c1ac88240e7694
license    : LGPL-2.1-or-later
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
