name       : syndication
version    : 17.12.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/syndication-17.12.3.tar.xz : 08a00ef0db70303c0e7b11aa6aeb84b3a76942981ac51e86fc5a2790231002af
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming.library
summary    : An RSS/Atom parser library
description: |
    syndication is a parser library for RSS and Atom feeds. syndication offers a unified, format-agnostic view on the parsed feed, so that the using application does not need to distinguish between feed formats.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
